# Generated by Django 2.2.16 on 2022-05-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
